var OFFLINE_STATUS_CHANGED = 'Offline/STATUS_CHANGED';
var OFFLINE_SCHEDULE_RETRY = 'Offline/SCHEDULE_RETRY';
var OFFLINE_COMPLETE_RETRY = 'Offline/COMPLETE_RETRY';
var OFFLINE_SEND = 'Offline/SEND';
var OFFLINE_BUSY = 'Offline/BUSY';
var RESET_STATE = 'Offline/RESET_STATE';
var PERSIST_REHYDRATE = 'persist/REHYDRATE';
var JS_ERROR = 'Offline/JS_ERROR';
var DEFAULT_COMMIT = 'Offline/DEFAULT_COMMIT';
var DEFAULT_ROLLBACK = 'Offline/DEFAULT_ROLLBACK';



export {
  OFFLINE_STATUS_CHANGED,
  OFFLINE_SCHEDULE_RETRY,
  OFFLINE_COMPLETE_RETRY,
  OFFLINE_SEND,
  OFFLINE_BUSY,
  RESET_STATE,
  PERSIST_REHYDRATE,
  JS_ERROR,
  DEFAULT_COMMIT,
  DEFAULT_ROLLBACK
}
